### ISSUE TITLE
Is except is available to use ** or *

### ISSUE THREAD

**Issue by ostk0069** [kawa1214/import-lint#38]
Here is what I want to do:

rule
```
    ignore_hoge_rule:
      target: "package:app/ui/**/*.dart"
      from: "package:app/ui/hoge.dart"
      except: 
        - "package:app/ui/fuga/fuga.dart" # ignore same package 
        - "package:app/ui/widget/**/*.dart" # ignore whole ui/widget directory from target
        - "package:app/ui/**/[!fuga_]*.dart" # ignore any file start with fuga_
        - "package:app/ui/**/*[!_screen].dart" # ignore any file end with _screen.dart
```

any of these except seems not working. If there are any way to work these except, please let me know.
